// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsmNlDdPEAxSWAHyciMtd9gDG8de6Jv88',
    appId: '1:880219495187:web:e3a202348765d3813a18e6',
    messagingSenderId: '880219495187',
    projectId: 'eduquest-e02f9',
    authDomain: 'eduquest-e02f9.firebaseapp.com',
    storageBucket: 'eduquest-e02f9.appspot.com',
    measurementId: 'G-JWXL2DVNYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwTNLhk7hwaDbciyhXEiXCf2DGSFMN14o',
    appId: '1:880219495187:android:25fe513b480feb5a3a18e6',
    messagingSenderId: '880219495187',
    projectId: 'eduquest-e02f9',
    storageBucket: 'eduquest-e02f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEAKtk67Z7pJCT_e1GjOyyvnfzKMqcBA',
    appId: '1:880219495187:ios:ad68848cf324e7f33a18e6',
    messagingSenderId: '880219495187',
    projectId: 'eduquest-e02f9',
    storageBucket: 'eduquest-e02f9.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNEAKtk67Z7pJCT_e1GjOyyvnfzKMqcBA',
    appId: '1:880219495187:ios:ad68848cf324e7f33a18e6',
    messagingSenderId: '880219495187',
    projectId: 'eduquest-e02f9',
    storageBucket: 'eduquest-e02f9.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsmNlDdPEAxSWAHyciMtd9gDG8de6Jv88',
    appId: '1:880219495187:web:81bea4ad66f15ed13a18e6',
    messagingSenderId: '880219495187',
    projectId: 'eduquest-e02f9',
    authDomain: 'eduquest-e02f9.firebaseapp.com',
    storageBucket: 'eduquest-e02f9.appspot.com',
    measurementId: 'G-PLHQ1G4YQ1',
  );
}
